# R syntax in a nutshell – Part II
* 1.6 Arrays, matrices, data frames
* 1.7 Building simple databases: indexing/subsetting of vectors, arrays and data frames
* 1.8 Lists
* 1.9 Coercion of individual object types

## 1.6	Arrays, matrices, data frames
Several kinds of table-like objects exist in R. **Data frames** are data objects to be processed by statistics, with “observations” as columns (elements/oxides in geochemistry) and “cases” (samples) in rows. They can contain columns of any mode, even mixed modes; thus they are not meant for matrix operations.

On the other hand, all elements of a **matrix** can only be of a single mode (numeric, most commonly). **Arrays** are generalized matrices: they must have a single mode but can have any number of dimensions. Although superficially similar, these three types of objects must not be confused.

#### matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE)
This command defines a matrix of `nrow` rows and `ncol` columns, filled by the data (if `data` have several elements, they will be used down the columns, unless an extra parameter `byrow=TRUE` is provided). For instance:

In [61]:
x <- matrix(1:12,3,4)
print(x)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


In [62]:
x <- matrix(1:12,3,4,byrow=TRUE)
print(x)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12


<img src="images/warning-icon.png" style="float:left;width:32px;height:32px;">
As a default, filling a matrix with data — as well as matrix division by a vector — proceeds along columns, not rows!

#### array(data = NA, dim = length(data))
Defines a new data array and fills it with `data`. The argument `dim` is a vector of length one or more, giving maximal dimensions in each of the directions.

### 1.6.1	Matrix/data frame operations
Matrices can be subject to scalar operations using the common operators (`+-*/^`). Similar to vectors, the shorter component is recycled as appropriate. Useful functions for matrix/data frame manipulations are summarized in the following Table:

<table>
    <tr>
    <th>Function</th>
    <th>Meaning</th>
    </tr>
    <tr><td>`nrow(x)`</td><td>number of rows</td></tr>
    <tr><td>`ncol(x)`</td><td>number of columns</td></tr>
    <tr><td>`rownames(x)` </td><td>row names</td></tr>
    <tr><td>`colnames(x)`</td><td>column names</td></tr>
    <tr><td>`rbind(x,y)`</td>
        <td>binds two objects (matrices or data frames) of the same `ncol`
        (or vectors of the same length) as rows
        </td></tr>
    <tr><td>`cbind(x,y)`</td>
        <td>binds two objects (matrices or data frames) of the same `nrow` 
        (or vectors of the same length) as columns
        </td></tr>
    <tr><td>`t(x)` </td><td>matrix transposition</td></tr>
    <tr><td>`apply(X,MARGIN,FUN)` </td>
    <td>applies function `FUN` (for vector manipulations) along the rows
    (`MARGIN` = 1) or columns (`MARGIN` = 2) of a data matrix `X`</td></tr>
    <tr><td>`x%*%y` </td>
        <td>matrix multiplication (does not work on a data frame!)</td></tr>
    <tr><td>`solve(A)`</td><td>matrix inversion</td></tr>
    <tr><td>`dix(x)`</td><td>diagonal elements of a matrix</td></tr>
</table>

It is worth noting that matrix multiplication is performed using the `%*%` operator. 

<img src="images/exercise-icon.png" style="float:left;width:40px;height:40px;">
The function `solve` can serve to solving a set of linear argebraic equations. Here is an example; let's first specify the matrix of coeffients to the individual variables:

In [63]:
A <- matrix(c(1,3,0.9,2,0.2,7,-0.7,-1,-2),3,3)
print(A) 

     [,1] [,2] [,3]
[1,]  1.0  2.0 -0.7
[2,]  3.0  0.2 -1.0
[3,]  0.9  7.0 -2.0


And then the vector of left hand sides:

In [64]:
y <- c(21,24,27)

In [65]:
x <- solve(A,y)
x

[1] 30 20 70

In [66]:
# checking the result, back-calculating y
A%*%x

[,1]
[1,]   21
[2,]   24
[3,]   27

Of the functions presented in the table, some explanation is required for `apply`:
#### apply(X, MARGIN, FUN,…)
If `X` is a matrix, it is split into vectors along rows (if `MARGIN` = 1) or columns (if `MARGIN` = 2). To each of these vectors is applied the function `FUN` with optional parameters `…` passed to it. 
For instance, we can calculate row sums of a matrix:

In [67]:
x <- matrix(1:12,3,4,byrow=TRUE)
x
apply(x,1,sum)

[,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12

[1] 10 26 42

## 1.7	Building simple databases: indexing/subsetting of vectors, arrays and data frames
In real life, one often needs to select some elements of a vector or a matrix, fulfilling certain criteria. This can be achieved using logical conditions or logical variables placed in **square brackets** after the object name. Subsets can be also used on the left hand side of the assignments when replacement of selected elements by certain values is desired.  
### 1.7.1	Vectors
Subsets of a vector may be selected by appending to the name of the vector an index vector in square brackets. For example, we can first create a named vector:

In [68]:
x <- c(1,12,15,NA,16,13,0,NA,NA)
names(x) <- c("Pl","Bt","Mu","Q","Kfs","Ky","Ol","Px","C") 
print(x)

 Pl  Bt  Mu   Q Kfs  Ky  Ol  Px   C 
  1  12  15  NA  16  13   0  NA  NA 


Index vectors can be of several types: logical, numeric (with positive or negative values), and character:

#### 1.	Logical vector

In [69]:
x[x>10]      # all elements of x higher than 10 (or NA)
x[!is.na(x)] # all elements of x that are available

Bt   Mu <NA>  Kfs   Ky <NA> <NA> 
  12   15   NA   16   13   NA   NA

Pl  Bt  Mu Kfs  Ky  Ol 
  1  12  15  16  13   0

#### 2.	Numeric vector with positive values

In [70]:
x[1:5]      # the first five elements
x[c(1,5,7)] # 1st, 5th and 7th elements

Pl  Bt  Mu   Q Kfs 
  1  12  15  NA  16

Pl Kfs  Ol 
  1  16   0

#### 3.	Numeric vector with negative values (specifies elements to be excluded)

In [71]:
x[-(1:5)] # all elements except for the first five

Ky Ol Px  C 
13  0 NA NA

#### 4.	Character vector (referring to the element names)

In [72]:
x[c("Q","Bt","Mu")]

Q Bt Mu 
NA 12 15

### 1.7.2	Matrices/data frames
Elements of a matrix are presented in the order `[row,column]`. If nothing is given for a `row` or `column`, it means no restriction. For instance:
```R
x[1,]          # (all columns) of the first row
x[,c(1,3)]     # (all rows) of the first and third columns
x[1:3,-2]      # all columns (apart from the 2nd) of rows 1–3
```
If the result is a single row or column, it is automatically converted to a vector. To prevent such a behaviour, one can supply an optional parameter `drop=FALSE`, e.g.:
```R
x[1,,drop=FALSE]   # (all columns) of the 1st row, keep as matrix
```

Moreover, matrices can be manipulated using index arrays. This concept is best explained on an example. Let’s assume a matrix defined as:
```R
x <- matrix(1:20,4,5)
```
If the elements `[1,3]`, `[2,2]` and `[3,1]` in `x` are to be replaced by zeroes, we can create an  index array `i` containing the element coordinates:

In [73]:
x <- matrix(1:20,4,5)
x
i <- matrix(c(1,2,3,3,2,1),3,2)
i

[,1] [,2] [,3] [,4] [,5]
[1,]    1    5    9   13   17
[2,]    2    6   10   14   18
[3,]    3    7   11   15   19
[4,]    4    8   12   16   20

[,1] [,2]
[1,]    1    3
[2,]    2    2
[3,]    3    1

In [74]:
x[i]

[1] 9 6 3

In [75]:
x[i] <- 0
x

[,1] [,2] [,3] [,4] [,5]
[1,]    1    5    0   13   17
[2,]    2    0   10   14   18
[3,]    0    7   11   15   19
[4,]    4    8   12   16   20

The situation for multidimensional arrays is analogous — just the relevant number of dimensions is higher than two.

<img src="images/exercise-icon.png" style="float:left;width:40px;height:40px;">
R involves numerous built in datasets that can be used to demonstrate its capabilities. The object `islands` is a vector with areas of landmassess (i.e. islands and continents) exceeding 10 000 sq. miles. Before we can start working, we need to attach the data object using the command: 

In [76]:
data(islands)

In [77]:
head(islands) # print just a few observations
islands["Luzon"]

Africa   Antarctica         Asia    Australia Axel Heiberg       Baffin 
       11506         5500        16988         2968           16          184

Luzon 
   42

In [78]:
mean(islands)

[1] 1252.729

In [79]:
names(islands)[islands==max(islands)]
print(which.max(islands))

[1] "Asia"

Asia 
   3 


In [80]:
max(islands)

[1] 16988

In [81]:
names(islands)[islands>5000]

[1] "Africa"        "Antarctica"    "Asia"          "North America"
[5] "South America"

In [82]:
z <- sort(islands)
print(z[1:15])

       Vancouver           Hainan  Prince of Wales            Timor 
              12               13               13               13 
          Kyushu           Taiwan      New Britain      Spitsbergen 
              14               14               15               15 
    Axel Heiberg         Melville      Southampton Tierra del Fuego 
              16               16               16               19 
           Devon            Banks            Celon 
              21               23               25 


In [83]:
out <- z[(length(z)-14):length(z)] # Or, alternatively:
print(out)
cat("\n")
out <- rev(sort(islands))[1:15]
print(out)

      Britain        Honshu       Sumatra        Baffin    Madagascar 
           84            89           183           184           227 
       Borneo    New Guinea     Greenland     Australia        Europe 
          280           306           840          2968          3745 
   Antarctica South America North America        Africa          Asia 
         5500          6795          9390         11506         16988 

         Asia        Africa North America South America    Antarctica 
        16988         11506          9390          6795          5500 
       Europe     Australia     Greenland    New Guinea        Borneo 
         3745          2968           840           306           280 
   Madagascar        Baffin       Sumatra        Honshu       Britain 
          227           184           183            89            84 


In [84]:
print(islands*2.59) #  recalculate the data to km2 (1 sq mi = 2.59 km2)

          Africa       Antarctica             Asia        Australia 
        29800.54         14245.00         43998.92          7687.12 
    Axel Heiberg           Baffin            Banks           Borneo 
           41.44           476.56            59.57           725.20 
         Britain          Celebes            Celon             Cuba 
          217.56           189.07            64.75           111.37 
           Devon        Ellesmere           Europe        Greenland 
           54.39           212.38          9699.55          2175.60 
          Hainan       Hispaniola         Hokkaido           Honshu 
           33.67            77.70            77.70           230.51 
         Iceland          Ireland             Java           Kyushu 
          103.60            85.47           126.91            36.26 
           Luzon       Madagascar         Melville         Mindanao 
          108.78           587.93            41.44            93.24 
        Moluccas      New Britain 

## 1.8	Lists
Lists are ordered collections of other objects, known as components, which do not have to be of the same mode or type. Thus lists can be viewed as very loose groupings of R objects, involving various types of vectors, data frames, arrays, functions and even other lists. 

Components are numbered and hence can be addressed using their sequence number given in double square brackets, `x[[3]]`. 
Moreover, components may be named and referenced using an expression of the form `list_name$component_name`. Subsetting is similar to that of other objects, described above.
#### list.name <- list (component_name_1=, component_name_2=…) 
Builds a list with the given components.

Here is a simple real-life example of a list definition:

In [85]:
x1 <- c("Luckovice","9 km E of Blatna","disused quarry")
x2 <- "melamonzonite"
x3 <- c(47.31,1.05,14.94,7.01,8.46,10.33)
names(x3) <- c("SiO2","TiO2","Al2O3","FeO","MgO","CaO")
luckovice <- list(ID="Gbl-4",Locality=x1,Rock=x2,major=x3)
luckovice

$ID
[1] "Gbl-4"

$Locality
[1] "Luckovice"        "9 km E of Blatna" "disused quarry"  

$Rock
[1] "melamonzonite"

$major
 SiO2  TiO2 Al2O3   FeO   MgO   CaO 
47.31  1.05 14.94  7.01  8.46 10.33

As well as some examples of subsetting:

In [86]:
luckovice[[1]]

[1] "Gbl-4"

In [87]:
luckovice$Rock # or luckovice[[3]]

[1] "melamonzonite"

In [88]:
luckovice[[2]][3]

[1] "disused quarry"

In [89]:
luckovice$major[c("SiO2","Al2O3")]

SiO2 Al2O3 
47.31 14.94

## 1.9	Coercion of individual object types
R is generally reasonably good at dealing seamlessly with data types, converting them on the fly when needed. When necessary, there are a series of functions for testing the mode (or type) of an object:
`is.numeric(x)`, `is.character(x)`, `is.logical(x)`, `is.matrix(x)`, `is.data.frame(x)`

At times there is a need to explicitly convert between data types/modes using functions such as:
`as.numeric(x)`, `as.character(x)`, `as.expression(x)`.

Less straightforward are:
`as.matrix(x)`, `as.data.frame(x)` 
which attempt to convert an object `x` to a matrix or data frame, respectively. 

A more user-friendly way of converting data frames to matrices is provided by the function `data.matrix` that converts all the variables in a data frame `x` to numeric mode and then binds them together as the columns of a matrix.